name: Process Options Data

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: "Link direto para download (.7z ou .txt)"
        required: false
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
          sudo apt-get update
          sudo apt-get install -y p7zip-full

      - name: Prepare folders
        run: |
          mkdir -p data outputs

      - name: Download data (if URL provided)
        if: ${{ github.event.inputs.download_url != '' }}
        run: |
          echo "Downloading from: ${{ github.event.inputs.download_url }}"
          curl -L "${{ github.event.inputs.download_url }}" -o data/input.bin
          file data/input.bin || true
          # Tenta extrair como .7z; se falhar, tenta unzip; se não for zip, assume .txt
          if 7z l data/input.bin >/dev/null 2>&1; then
            7z x -odata data/input.bin
          elif unzip -l data/input.bin >/dev/null 2>&1; then
            unzip -o data/input.bin -d data/
          else
            mv data/input.bin data/input.txt
          fi
          ls -lah data || true

      - name: Process all .txt files in data/
        run: |
          shopt -s nullglob
          for f in data/*.txt; do
            echo "Processing $f"
            out="outputs/$(basename "${f%.txt}").csv"
            python scripts/extract_options.py --in "$f" --out "$out" --sep "(\\t|,\\s+)"

          done
          ls -lah outputs || true

      - name: Upload CSVs
        uses: actions/upload-artifact@v4
        with:
          name: processed-csvs
          path: outputs/*.csv
          if-no-files-found: warn
